### ISSUE TITLE
Empty and reseed ThesisCentral database for class of 2021 (QA)

### ISSUE THREAD

**Issue by kelynch** [pulibrary/drds_catchall#24]
Empty and reseed the thesiscentral-qa database with HR people feed (James, Bess, and Kate all receive this twice a week) based on instructions in the [readme](https://github.com/PrincetonUniversityLibrary/thesiscentral-vireo/blob/d3347a091ee69793f498acd4df7ffb0aaeba2dc7/README.md#princeton-modifications).

## Acceptance Criteria

- [x] Database contains no 2020 data
- [x] Database contains all 2021 student data with modified email addresses
- [ ] RDSS staff and Lynn can log in

@kelynch is going to ask Lynn to try logging into the QA system. Assuming it is good to go, we'll move onto production.

**Comment by jrgriffiniii** [comment]
I have just tested and confirmed that the QA server is available using the `lib200w` Windows Server bastion host. One will require an OIT service account in order to access this, and one must use a client supporting the Remote Desktop Protocol.

**Comment by jrgriffiniii** [comment]
From the bastion host, one uses the PuTTY client in order to access the current ThesisCentral servers themselves (these are hosted using Amazon Web Services, likely as EC2 instances).

I must use a separate, older OIT service account in order to access these servers over PuTTY. Currently, these servers use a release of Red Hat Enterprise Linux.

**Comment by kelynch** [comment]
Awaiting stakeholder feedback; will open a new ticket in the event that there are issues reported.
